### ARRAYS

##### Arrays are 1-based and column-major (like Octave and MATLAB)

In [39]:
a = [1, 2, 3]              # 1D row vector


3-element Vector{Int64}:
 1
 2
 3

In [41]:
b = [1; 2; 3]              # 1D column vector

3-element Vector{Int64}:
 1
 2
 3

In [47]:
a==b

true

In [45]:
c = [1 2; 3 4]             # 2x2 matrix

2×2 Matrix{Int64}:
 1  2
 3  4

In [5]:
a[1]      #indexing from 1

1

In [49]:

w=[1 2 3]

1×3 Matrix{Int64}:
 1  2  3

#### εξήγηση

#### In Julia, the difference between:

a = [1 2 3]

w = [1, 2, 3]

is in the
#### dimensions (shape) of the resulting arrays:

🔹 a = [1 2 3]

This creates a 2D row matrix of size 1×3.

Type: Matrix{Int64}

In [15]:
a=[1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [17]:
w=[1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [19]:
y=[1;2;3]

3-element Vector{Int64}:
 1
 2
 3

In [21]:
y==w


true

In Julia, the behavior of semicolons can 
#### depend on context, especially when used inside array constructors.

Let’s carefully and correctly distinguish these cases:

In [24]:
y = [1; 2; 3]

3-element Vector{Int64}:
 1
 2
 3

Result: Vector{Int64}

Shape: (3,) → a 1D vector, not a 3×1 matrix.

Julia "flattens" the semicolon-separated values into a 1D vector when all elements are scalars. This is different from what many expect coming from 
##### This is different from what many expect coming from MATLAB/Octave.



In [26]:
m = [[1]; [2]; [3]]

3-element Vector{Int64}:
 1
 2
 3


####  Correct Ways to Create a 3×1 Matrix
✅ Method 1: 
### Use reshape



In [30]:
reshape([1, 2, 3], 3, 1)

3×1 Matrix{Int64}:
 1
 2
 3

#### Method 2

#### Direct matrix construction


In [36]:
m = [1 2 3]'   # transpose a row vector

3×1 adjoint(::Matrix{Int64}) with eltype Int64:
 1
 2
 3

✅ Comparison
Feature	Julia	Octave
1-based index	✅	✅
Column-major	✅	✅       way  they ate put in memory
Dynamic sizes	✅ (push!)	✅ (end+1)

#### Indexing & Slicing


In [55]:
a = [10, 20, 30, 40]

4-element Vector{Int64}:
 10
 20
 30
 40

In [57]:
a[1]

10

In [59]:
a[2:3]

2-element Vector{Int64}:
 20
 30

In [61]:
a[end]

40

#### Octave : IDEM except parenthesis instead of []

a = [10, 20, 30, 40];
a(1)             % 10
a(2:3)           % [20, 30]
a(end)           % 40

### Ranges

### Ranges
📌 Julia

1:5              # 1, 2, 3, 4, 5 (unit step)
1:2:9            # 1, 3, 5, 7, 9
📌 Octave

1:5              % 1, 2, 3, 4, 5
1:2:9            % 1, 3, 5, 7, 9

#### Identical syntax for colon operator.

### Linear Spacing (linspace equivalent)

In [64]:
range(1, stop=5, length=5) 

1.0:1.0:5.0

In [66]:
range(1, stop=2, length=7)

1.0:0.16666666666666666:2.0

In [69]:
collect(range(start=1, stop=5, length=5))

5-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0
 5.0

In [71]:
collect(range(1, stop=5, length=5))   # start above was optional


5-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0
 5.0

#### Matrix Creation Functions

 Matrix Creation Functions
Operation	Julia	Octave
Zeros	zeros(3, 2)	zeros(3, 2)
Ones	ones(2, 3)	ones(2, 3)
Identity matrix	I (unit range) or Matrix{Float64}(I, 3, 3)	eye(3)
Random matrix	rand(3, 3)	rand(3, 3)

In [77]:
x=zeros(2,3)

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [79]:
y=ones(3,2)

3×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0
 1.0  1.0

#### Identity Matrix

In [86]:
I(3,3)

LoadError: UndefVarError: `I` not defined

In [88]:
Matrix{Float64}(I, 3, 3)  # 3×3 concrete identity matrix

LoadError: UndefVarError: `I` not defined

In [90]:
Matrix{Int}(I, 3, 3)

LoadError: UndefVarError: `I` not defined

In [92]:
using LinearAlgebra
Matrix(I, 3, 3)

3×3 Matrix{Bool}:
 1  0  0
 0  1  0
 0  0  1

In [94]:
Matrix{Int}(I, 3, 3)     ### after usin Linear Algebra

3×3 Matrix{Int64}:
 1  0  0
 0  1  0
 0  0  1

### random

In [97]:
rand(3,3)

3×3 Matrix{Float64}:
 0.244555  0.157787  0.32189
 0.857501  0.941878  0.898591
 0.111881  0.192304  0.0698448

#### Modifying Arrays

In [101]:
a = [1, 2, 3]
push!(a, 4)

4-element Vector{Int64}:
 1
 2
 3
 4

In [103]:
pop!(a)

4

In [105]:
a


3-element Vector{Int64}:
 1
 2
 3

In [107]:
append!(a, [5, 6])

5-element Vector{Int64}:
 1
 2
 3
 5
 6

#### Broadcasting (Element-wise)

In [110]:
a = [1, 2, 3]
b = a .^ 2          # [1, 4, 9]

3-element Vector{Int64}:
 1
 4
 9

In [112]:
s=[1 2 3]
t=s.^2

1×3 Matrix{Int64}:
 1  4  9