# Linear Algebra

#### In Julia, rand(1:4, 3, 3) generates a 3×3 matrix filled with random integers sampled from the range 1:4 (i.e., each element can be 1, 2, 3, or 4). Here's a detailed breakdown:

In [3]:
rand(1:4 , 3 , 3)

3×3 Matrix{Int64}:
 2  1  1
 4  1  4
 4  3  3

In [5]:
rand(1:4 , 3 , 3)   ## another matrix


3×3 Matrix{Int64}:
 2  2  1
 2  1  1
 4  1  2

In [7]:
Random.seed!(123) ##  before calling rand to get the same results every time.

LoadError: UndefVarError: `Random` not defined

In [9]:
rand(1:4)	## Single random integer (1, 2, 3, or 4)	Scalar output.

1

In [11]:
rand(1:4, 5)	### 5-element Vector{Int64}

5-element Vector{Int64}:
 2
 1
 2
 3
 1

In [13]:
rand(1:4, (2, 3))	### 2×3 Matrix{Int64}

2×3 Matrix{Int64}:
 2  4  3
 3  4  4

In [15]:
A = rand(1:4,3,3)

3×3 Matrix{Int64}:
 1  2  4
 2  4  1
 2  4  4

In [17]:
B = A

3×3 Matrix{Int64}:
 1  2  4
 2  4  1
 2  4  4

In [19]:
B

3×3 Matrix{Int64}:
 1  2  4
 2  4  1
 2  4  4

In [21]:
C = copy(A)

3×3 Matrix{Int64}:
 1  2  4
 2  4  1
 2  4  4

In [23]:
C

3×3 Matrix{Int64}:
 1  2  4
 2  4  1
 2  4  4

In [25]:
[B C]

3×6 Matrix{Int64}:
 1  2  4  1  2  4
 2  4  1  2  4  1
 2  4  4  2  4  4

In [27]:
A[1] = 17

17

In [29]:
A

3×3 Matrix{Int64}:
 17  2  4
  2  4  1
  2  4  4

In [33]:
[B C]

3×6 Matrix{Int64}:
 17  2  4  1  2  4
  2  4  1  2  4  1
  2  4  4  2  4  4

In [35]:
x=ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [37]:
b = A*x  ###  (3x3)*(3x1)=3x1

3-element Vector{Float64}:
 23.0
  7.0
 10.0

### TRANSPOSITION
#### In other languages A' is the conjugate transpose.
#### A' is Just TRANSPOSE

In [40]:
A'


3×3 adjoint(::Matrix{Int64}) with eltype Int64:
 17  2  2
  2  4  4
  4  1  4

In [42]:
b'

1×3 adjoint(::Vector{Float64}) with eltype Float64:
 23.0  7.0  10.0

In [ ]:
In Julia, there is no separate "row vector" type, but you can work with row-like behavior 
    using the adjoint operation ('). Here’s what’s happening in your example:

1. What is adjoint?
The adjoint of a vector (or matrix) is its conjugate transpose:

For real numbers (no complex part), adjoint == transpose (turns columns into rows).

For complex numbers, it also takes the complex conjugate.

Syntax:

x' is shorthand for adjoint(x).

transpose(x) is similar but does not conjugate (preferred for real numbers).

In [44]:
transpose(b')

3-element Vector{Float64}:
 23.0
  7.0
 10.0

In [46]:
b''

3-element Vector{Float64}:
 23.0
  7.0
 10.0

### ✅ 1. Definitions
### 🔁 Transpose (transpose(A) or A.')
#### Swaps rows and columns.

#### Does not conjugate complex numbers.

### 🧲 Adjoint / Conjugate Transpose (adjoint(A) or A')
#### Swaps rows and columns and takes the complex conjugate of each element.



In [49]:

### REALS

A = [1 2; 3 4]

transpose(A)   # or A'



2×2 transpose(::Matrix{Int64}) with eltype Int64:
 1  3
 2  4

In [51]:
adjoint(A)     # or A'
# Output: same as above for real numbers
# 2×2 Matrix{Int64}:
# 1  3
# 2  4

2×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  3
 2  4

### For real numbers (no complex part),
### adjoint == transpose (turns columns into rows).

In [54]:
B = [1+2im 3; 4 5+6im]

transpose(B)   # or B.'

2×2 transpose(::Matrix{Complex{Int64}}) with eltype Complex{Int64}:
 1+2im  4+0im
 3+0im  5+6im

In [56]:
adjoint(B)

2×2 adjoint(::Matrix{Complex{Int64}}) with eltype Complex{Int64}:
 1-2im  4+0im
 3+0im  5-6im

In [58]:
B'

2×2 adjoint(::Matrix{Complex{Int64}}) with eltype Complex{Int64}:
 1-2im  4+0im
 3+0im  5-6im

In [60]:
A'

2×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  3
 2  4

Summary Table
Operation	Syntax	Swaps Rows & Columns	Conjugates Complex Values
Transpose	A.' or transpose(A)	✅ Yes	❌ No
Adjoint	    A'  or adjoint(A)	✅ Yes	✅ Yes

### Use Cases
A' (adjoint) is used in linear algebra, especially for:

Inner products

Hermitian matrices (A == A')

Unitary matrices (A' * A == I)

transpose(A) is used when:

You need to manipulate the layout but not conjugate.

#### Common Mistake
If A has complex entries and you write A' instead of transpose(A), you’ll accidentally conjugate the entries. Always double-check!

In [ ]:
How to Convert to a True Matrix (If Needed)
If you explicitly want a 1×3 matrix (not a lazy adjoint):

julia
julia> row_vec = reshape(x, 1, :)  # 1×3 Matrix
1×3 Matrix{Float64}:
 23.0  7.0  10.0

julia> transpose(x)  # Explicit transpose (no conjugation)
1×3 transpose(::Vector{Float64}) with eltype Float64:
 23.0  7.0  10.0


Why Does Julia Use Adjoint Instead of Row Vectors?
Performance: Avoids unnecessary memory allocation.

Consistency: Handles complex numbers correctly (unlike a naive transpose).

Flexibility: Works seamlessly in linear algebra (e.g., A * x' is valid if dimensions match).

In [69]:
A = rand(0:2,3, 3)

3×3 Matrix{Int64}:
 2  0  2
 1  1  0
 0  1  1

In [67]:

x = rand(0:2,3)

3-element Vector{Int64}:
 0
 1
 1

In [71]:
A * x

3-element Vector{Int64}:
 2
 1
 2

In [74]:
x'*A

1×3 adjoint(::Vector{Int64}) with eltype Int64:
 1  2  1

### Inner/Outer Products

#### dot(x, y) == x' * y  .....        Inner product (scalar)
#### x * y'               .....        Outer product (matrix)

In [ ]:
 Why No RowVector Type?
Julia’s design avoids dedicated row vectors because:

Adjoint/Transpose are sufficient for math operations.

Reduces type complexity (no need for RowVector + Matrix).

Follows the principle: "Row vectors are just transposed columns."

Summary
x' (adjoint) is Julia’s way of representing row vectors without allocating new memory.

It’s a view, not a copy, and behaves like a row in linear algebra.

For explicit row matrices, use reshape or transpose.

This design balances performance, correctness, and simplicity.



## Jane

### As in other languages A' is the CONJUGATE TRANSPOSE, 
### whereas A.' is deprecated => 
## transpose(A) now

In [83]:
B = [1+2im 3; 4 5+6im]

2×2 Matrix{Complex{Int64}}:
 1+2im  3+0im
 4+0im  5+6im

In [91]:
B'

2×2 adjoint(::Matrix{Complex{Int64}}) with eltype Complex{Int64}:
 1-2im  4+0im
 3+0im  5-6im

In [87]:
B.'

LoadError: ParseError:
# Error @ ]8;;file:///home/pacos/Documents/PROJECTS/Jupyter-Lab/JULIA/GentleJane/In[87]#1:2\In[87]:1:2]8;;\
B.'
#└┘ ── the .' operator for transpose is discontinued

In [ ]:
In Julia, the .' operator (used for transposing matrices) was deprecated and later removed. Here’s what happened:

Old Syntax (Pre-Julia 1.0):

A.' was used for non-conjugate (simple) transpose.

Example: B = [1 2; 3 4]; B.' would return [1 3; 2 4].

New Syntax (Julia 1.0+):

.' was replaced with transpose(A) for clarity and consistency.

The ' operator (adjoint) is now reserved for conjugate transpose (relevant for complex numbers).



In [ ]:
B_complex = [1+2im 3+4im; 5+6im 7+8im]
2×2 Matrix{Complex{Int64}}:
 1+2im  3+4im
 5+6im  7+8im

julia> B_complex'  # Conjugate transpose
2×2 adjoint(::Matrix{Complex{Int64}}) with eltype Complex{Int64}:
 1-2im  5-6im
 3-4im  7-8im

julia> transpose(B_complex)  # Just transpose (no conjugation)
2×2 transpose(::Matrix{Complex{Int64}}) with eltype Complex{Int64}:
 1+2im  5+6im
 3+4im  7+8im
Key Takeaways
Operation	Syntax	Behavior
Transpose	transpose(A)	Swaps rows and columns (no conjugation).
Adjoint	A'	Conjugate transpose (use for complex).
Deprecated	A.'	No longer works (throws ParseError).
Why Was .' Removed?
Avoid Confusion: .' looked like broadcasting (e.g., A .+ B).

Explicitness: transpose(A) is clearer than A.'.

Consistency: ' now strictly means conjugate transpose (standard in math).

What to Do If You See Legacy Code
Replace all instances of A.' with:

transpose(A) for simple transposes.

A' if conjugate transpose is intended (and the matrix is complex).

Example Fix
Before (Broken):

julia
B = [1 2; 3 4]
B.'  # Throws ParseError
After (Fixed):

julia
B = [1 2; 3 4]
transpose(B)  # Works!
Summary
Use transpose(A) for non-conjugate transposes.

Use A' for conjugate transposes (or real matrices where it doesn’t matter).

Never use A.'—it’s discontinued in modern Julia.

This change makes Julia’s linear algebra syntax clearer and more consistent! 🚀



## Ax = b

In Julia, the linear system 

Ax=b (where A is a square matrix and 

b is a vector) can be solved efficiently using built-in functions from 
#### the standard library or 
### optimized packages like LinearAlgebra
#### Using the Backslash Operator \ operator, which dispatches to the best solver based on A's properties.

In [100]:
using LinearAlgebra

# Define A (square matrix) and b (vector)
A = [1 2; 3 4]  # 2×2 matrix
b = [5, 6]      # 2-element vector

# Solve for x
x = A \ b

2-element Vector{Float64}:
 -3.9999999999999987
  4.499999999999999

In [104]:
### verification 
A*x

2-element Vector{Float64}:
 5.0
 6.0

####  Meaning of A[:, 1:2]
: (colon) selects all rows.

1:2 selects columns 1 to 2 (inclusive).

Result: A new matrix containing 
##### all rows but only columns 1 and 2 of A
#### Atall = A[: , 1:2]

In [108]:
A = [1 2 3; 4 5 6; 7 8 9]  # 3×3 matrix


3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [110]:
A[:, 1:2]  # All rows, columns 1-2


3×2 Matrix{Int64}:
 1  2
 4  5
 7  8

In [112]:
A[:, 2]   # All rows, only column 2

3-element Vector{Int64}:
 2
 5
 8

In [114]:
A[2:3, :]	# Rows 2-3, all columns	2×3 matrix

2×3 Matrix{Int64}:
 4  5  6
 7  8  9

In [116]:
A[[1,3], 1:2]	# Rows 1 and 3, columns 1-2	2×2 matrix

2×2 Matrix{Int64}:
 1  2
 7  8

In [142]:
## RAPPEL
A = [i + 3*j for j in 0:2 , i in 1:3]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [144]:
A = [i + 3*j for j i = 0:2 , i i = 1:3]

LoadError: ParseError:
# Error @ ]8;;file:///home/pacos/Documents/PROJECTS/Jupyter-Lab/JULIA/GentleJane/In[144]#1:19\In[144]:1:19]8;;\
A = [i + 3*j for j i = 0:2 , i i = 1:3]
#                 └──────┘ ── invalid iteration spec: expected one of `=` `in` or `∈`

In [146]:
n=1:4

1:4

In [148]:
n in 1:4

false

In [150]:
n


1:4

In [152]:
z=1:3

1:3

### Factorization

#### Factorization is a fundamental operation in linear algebra that decomposes a matrix into a 
#### product of matrices. 
### LU Factorization.....από το Lower & Upper                   
#### LU factorization decomposes a matrix into a lower triangular matrix (L) and an upper triangular matrix

In [157]:
using LinearAlgebra
A = [4.0 3.0; 6.0 3.0]
lu_fact = lu(A)  # LU factorization

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
2×2 Matrix{Float64}:
 1.0       0.0
 0.666667  1.0
U factor:
2×2 Matrix{Float64}:
 6.0  3.0
 0.0  1.0

In [159]:
L = lu_fact.L

2×2 Matrix{Float64}:
 1.0       0.0
 0.666667  1.0

In [161]:
U = lu_fact.U

2×2 Matrix{Float64}:
 6.0  3.0
 0.0  1.0

### QR Factorization
#### QR factorization decomposes a matrix into an orthogonal matrix (Q) and an upper triangular matrix (R).

In [167]:
A = [1.0 2.0; 3.0 4.0; 5.0 6.0]


3×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0
 5.0  6.0

In [169]:
qr_fact = qr(A)  # QR factorization

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor: 3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}
R factor:
2×2 Matrix{Float64}:
 -5.91608  -7.43736
  0.0       0.828079

In [173]:
Q = qr_fact


LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor: 3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}
R factor:
2×2 Matrix{Float64}:
 -5.91608  -7.43736
  0.0       0.828079

In [175]:
R = qr_fact.R

2×2 Matrix{Float64}:
 -5.91608  -7.43736
  0.0       0.828079